# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY controllers controllers/
COPY models/ models/
COPY main.go ./

RUN go build -o /prescriptions

##
## Deploy
##
## https://sysdig.com/blog/dockerfile-best-practices/
FROM gcr.io/distroless/static-debian10

USER nonroot:nonroot

COPY --from=build /prescriptions /prescriptions

EXPOSE 8080

ENV GIN_MODE=release

ENTRYPOINT ["/prescriptions"]
